function showFlyout(anchor,flyout,keepPrevious,offset,mask){var $flyout=$(flyout);if(!$flyout.length){return}
if(!$flyout.parent().is("body")){$flyout.appendTo("body")}
try{trailOff2()}catch(e){}
if(mask){if($("#flyout_mask").length==0){$('<div id="flyout_mask" style="display: block; position: fixed; position: absolute; top: 0; left: 0; width: 100%; min-height: 100%; height: 100%; background: #000000; border: 1px solid #cecece; z-index: 40; opacity: 0.4; filter: alpha(opacity=40);"></div>').appendTo("body")}
$("#flyout_mask").height($(document).height())}
offset=offset||0;var flyoutWidth=$flyout.width();var flyoutHeight=$flyout.height();var windowWidth=$(window).width();var windowHeight=$(window).height();var scrollLeft=$(document).scrollLeft();var scrollTop=$(document).scrollTop();var $anchor,anchorLeft,anchorTop,anchorWidth,anchorHeight;if(anchor==="center"){anchorLeft=scrollLeft+(windowWidth-flyoutWidth)/2;anchorTop=scrollTop+windowHeight/2;anchorWidth=0;anchorHeight=0}else{$anchor=$(anchor);if(!$anchor.length){return}
anchorLeft=$anchor.offset().left;anchorTop=$anchor.offset().top;anchorWidth=$anchor.width();anchorHeight=$anchor.height()}
var flyoutLeft=0;var flyoutTop=0;var left,top,handle,handleLeft,handleTop;if(anchorLeft+anchorWidth+flyoutWidth<scrollLeft+windowWidth){left=anchorLeft+anchorWidth+offset;top=Math.max(scrollTop,Math.min(scrollTop+windowHeight-flyoutHeight,(anchorTop+anchorHeight/2-flyoutHeight/2)));handle=".dt-commentboxflyarr-l-lb";handleLeft="";handleTop=Math.max(5,Math.min(flyoutHeight-10,anchorTop-top+anchorHeight/2-5))}else if(anchorLeft-flyoutWidth>scrollLeft){left=anchorLeft-flyoutWidth-offset;top=Math.max(scrollTop,Math.min(scrollTop+windowHeight-flyoutHeight,(anchorTop+anchorHeight/2-flyoutHeight/2)));handle=".dt-commentboxflyarr-r-lb";handleLeft="";handleTop=Math.max(5,Math.min(flyoutHeight-10,anchorTop-top+anchorHeight/2-5))}else if(anchorTop+anchorHeight+flyoutHeight<scrollTop+windowHeight){left=Math.max(scrollLeft,Math.min(scrollLeft+windowWidth-flyoutWidth,(anchorLeft+anchorWidth/2-flyoutWidth/2)));top=anchorTop+anchorHeight+offset+5;handle=".dt-commentboxflyarr-t-lb";handleLeft=Math.max(5,Math.min(flyoutWidth-10,anchorLeft-left+anchorWidth/2-5));handleTop=""}else{left=Math.max(scrollLeft,Math.min(scrollLeft+windowWidth-flyoutWidth,(anchorLeft+anchorWidth/2-flyoutWidth/2)));top=anchorTop-flyoutHeight-offset-5;handle=".dt-commentboxflyarr-b-lb";handleLeft=Math.max(5,Math.min(flyoutWidth-10,anchorLeft-left+anchorWidth/2-5));handleTop=""}
$(".dt-commentboxflyarr-l-lb, .dt-commentboxflyarr-r-lb, .dt-commentboxflyarr-t-lb, .dt-commentboxflyarr-b-lb",$flyout).hide();if(handleLeft){handleLeft+='px'}
if(handleTop){handleTop+='px'}
if(mask&&!$("#flyout_mask").is(":visible")){$("#flyout_mask").fadeIn()}
if(keepPrevious||$(".dt-commentboxfly-lb").not($flyout).length==0){$(handle,$flyout).css({position:'absolute',left:handleLeft,top:handleTop}).fadeIn();$flyout.css({position:'absolute',zIndex:41,left:left+'px',top:top+'px'}).fadeIn(function(){setTimeout(function(){$(document).unbind('click',hideFlyout).bind('click',hideFlyout);$("textarea, input[type='text'], input[type='password']",$flyout).first().focus()},100)})}else{$(".dt-commentboxfly-lb").not($flyout).fadeOut(function(){$(handle,$flyout).css({position:'absolute',left:handleLeft,top:handleTop}).fadeIn();$flyout.css({position:'absolute',zIndex:41,left:left+'px',top:top+'px'}).fadeIn(function(){setTimeout(function(){$(document).unbind('click',hideFlyout).bind('click',hideFlyout);$("textarea, input[type='text'], input[type='password']",$flyout).first().focus()},100)})})}}
function hideFlyout(event){if(event&&$(event.target).is(".dt-commentboxfly-lb *")&&!$(event.target).is(".dt-commentboxflyclose-lb")){return!0}
$(".dt-commentboxfly-lb, #flyout_mask").fadeOut();if(event){event.stopImmediatePropagation();event.preventDefault()}
$(document).unbind('click',hideFlyout)}
function makeDropdown(container,onchange,selectors){selectors=selectors||{};selectors.cur=selectors.cur||"span";selectors.arr=selectors.arr||"a";selectors.list=selectors.list||"div";selectors.opt=selectors.opt||"div a";$(container).each(function(){var $container=$(this);var $cur=$(selectors.cur,$container);var $arr=$(selectors.arr,$container);var $list=$(selectors.list,$container);var $opt=$(selectors.opt,$container);if(!makeDropdown.lists){makeDropdown.lists=$($list.get(0))}else{makeDropdown.lists=makeDropdown.lists.add($($list.get(0)))}
$(document).click((function($container,$cur,$arr,$list,$opt,onchange){return function(e){var $target=$(e.target);if($target.closest($container).length==0){$list.hide();return}
makeDropdown.lists.not($list).hide();if($target.is($opt)){$cur.html($target.html());$list.hide();onchange.apply(e.target);e.preventDefault();e.stopImmediatePropagation();return}
if($target.is($container)||$target.is($cur)||$target.is($arr)){$list.toggle();e.preventDefault();e.stopImmediatePropagation();return}}})($container,$cur,$arr,$list,$opt,onchange))})}
function showConfirmFlyout(anchor,flyout,title,message,yesCallback,noCallback,dnsid){var flyoutdns="";if(dnsid&&typeof getCookie=="function"){flyoutdns="|"+dnsid+"|"}
if(flyoutdns){var donotshow=getCookie("cfdns")||"";if(donotshow.indexOf(flyoutdns)!=-1){if(typeof yesCallback=="function"){yesCallback()}
return}}
$(".flyout_yes",flyout).unbind('click').bind('click',function(e){e.stopImmediatePropagation();e.preventDefault();if(yesCallback){yesCallback.apply(e.target,[e])}
if($(".dt-commentboxfly-lb:visible").length==1){$(document).unbind('click',hideFlyout)}
$(flyout).fadeOut();return!1});$(".flyout_no",flyout).unbind('click').bind('click',function(e){e.stopImmediatePropagation();e.preventDefault();if(noCallback){noCallback.apply(e.target,[e])}
if($(".dt-commentboxfly-lb:visible").length==1){$(document).unbind('click',hideFlyout)}
if(flyoutdns){var donotshow=getCookie("cfdns")||"";donotshow=donotshow.replace(flyoutdns,"");setCookie("cfdns",donotshow,1/24/12)}
$(flyout).fadeOut();return!1});$(".flyout_title",flyout).html(title);$(".flyout_message",flyout).html(message);if(flyoutdns){$(".flyout_donotshow",flyout).unbind('change').bind('change',function(e){e.stopImmediatePropagation();e.preventDefault();var donotshow=getCookie("cfdns")||"";donotshow=donotshow.replace(flyoutdns,"");if($(this).prop('checked')){donotshow+=flyoutdns}
setCookie("cfdns",donotshow,1/24/12)})}
showFlyout(anchor,flyout,!0)}
$(document).ready(function(){$('<div id="imgtrailer" style="position:absolute;visibility:hidden;z-index:2000;"></div>').appendTo('body')});function gettrailobject(){return document.getElementById("imgtrailer")}
function gettrailobj(){var obj=gettrailobject();if(typeof obj=="object"&&obj!=null){return obj.style}}
var divw=0;var divh=0;document.onmousemove=function manageonmousemove(e){mouseEvent=e};var mouseEvent=!1;function followmouse(e){if(!e)
e=mouseEvent;if(!gettrailobj()){return}
var docwidth=$(window).width();var docheight=$(window).height();var right=!1;if(typeof e!="undefined"){if(docwidth<15+e.pageX+divw){xcoord=e.pageX-divw-5;right=!0}else{xcoord=15+e.pageX}
if(docheight<15+e.pageY+divh){ycoord=15+e.pageY-Math.max(0,(divh+e.pageY-docheight-$(document).scrollTop()-30))}else{ycoord=15+e.pageY}}else if(typeof window.event!="undefined"){if(docwidth<15+$(document).scrollLeft()+event.clientX+divw){xcoord=$(document).scrollLeft()-5+event.clientX-divw;right=!0}else{xcoord=$(document).scrollLeft()+15+event.clientX}
if(docheight<15+$(document).scrollTop()+event.clientY+divh){ycoord=15+$(document).scrollTop()+event.clientY-Math.max(0,(divh+event.clientY-docheight-30))}else{ycoord=$(document).scrollTop()+15+event.clientY}}
gettrailobj().left=xcoord+"px";gettrailobj().top=ycoord+"px";if(right!=$("#btcontainer").data('right')){$("#btcontainer").data('right',right);var imgid=$("#btcontainer").data('imgid');if(imgid){if(typeof followmouse.pinimg=="undefined"){followmouse.pinimg=null;followmouse.pinimg=$("body > span[style*='position: absolute'][style*='background: url']");if(followmouse.pinimg&&followmouse.pinimg.length==0){followmouse.pinimg=$("body > span[style*='position: absolute'][style*='background-image: url']")}
if(followmouse.pinimg&&followmouse.pinimg.length==0){followmouse.pinimg=null}
if(followmouse.pinimg){followmouse.pinimg.css("z-index","98")}}}}}
function trailOnV(thumbimg,imgid,thw,thh,smallThumbPath,imgtitle,delayhover){if(!gettrailobj()){return}
if(trailOff2.th===this){return}
thumbimgprev=smallThumbPath;imgtitle=$("[id^=spn"+imgid+"] span").text()||imgtitle;$("[id^=spn"+imgid+"]").each(function(){setImportantStyle(this,{display:'none'})});gettrailobj().left="-500px";divthw=parseInt(thw)+2;smthw=parseInt(thw)+2;halfthh=50;halfthh=Math.ceil(parseInt(thh)/2);topx=halfthh-9;smthh=parseInt(thh)+3;var length=10;if(navigator.userAgent.indexOf("MSIE")!=-1){htm2='margin:0px;width:'+thw+'px;height:100%;z-index:53;layer-background-color: #FFFFFF;background-color:#4c4843;padding:8 5px 0 5px;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:center;'}else{htm2='border-width:0px;width:'+thw+'px;margin:0px;z-index:53;layer-background-color: #FFFFFF;background-color:#4c4843;padding:8px 5px 0 5px;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;'}
htm='';htm+='<div style="border: 10px solid #4c4843; background: #4c4843; width:'+thw+'px;height:100%;position:absolute; display:table; z-index:49; ">';htm+='<div name="btcontainer" id="btcontainer" style="background-color:#4c4843;border: 1px solid #4c4843;display:block; font-size: 0.1px;">';htme='<video poster="'+thumbimgprev+'" id="sampleMovie" width="'+thw+'" height="100%" preload="metadata" autoplay muted>';htme+='<source src="//thumbs.dreamstime.com/videothumb_'+Math.floor(imgid/10000)+'/'+imgid+'.mp4" type=\'video/mp4; codecs="avc1.42E01E, mp4a.40.2"\'  />';htme+='<source src="//thumbs.dreamstime.com/videothumb_'+Math.floor(imgid/10000)+'/'+imgid+'.webm" type=\'video/webm; codecs="vp8, vorbis"\'  />';htme+='<object width="'+thw+'" height="'+thh+'" type="application/x-shockwave-flash" data="/flashmediaelement.swf">';htme+='<param name="movie" value="//fpdownload.adobe.com/strobe/FlashMediaPlayback.swf"></param>';htme+='<param name="flashvars" value="src=%2F%2Fthumbs.dreamstime.com%2Fvideothumb_'+Math.floor(imgid/10000)+'%2F'+imgid+'.flv&autoPlay=true"></param>';htme+='<param name="allowFullScreen" value="true"></param>';htme+='<param name="allowscriptaccess" value="always"></param>';htme+='<param name="autoStart" value="1"></param>';htme+='<param name="autoPlay" value="1"></param>';htme+='<param name="wmode" value="transparent"></param>';htme+='<embed src="//fpdownload.adobe.com/strobe/FlashMediaPlayback.swf"';htme+=' type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" autoPlay="true" wmode="transparent"';htme+='width="'+thw+'" height="'+thh+'" flashvars="src=%2F%2Fthumbs.dreamstime.com%2Fvideothumb_'+Math.floor(imgid/10000)+'%2F'+imgid+'.flv&autoPlay=true">';htme+='</embed>';htme+='</object>';htme+='</video>';html='</div>';html+='<div id="div_2" style="'+htm2+'">'+imgtitle+'</div>';html+='</div>';gettrailobject().innerHTML=htm+htme+html;if(delayhover){if(trailOff2.t){clearTimeout(trailOff2.t)}
trailOff2.t=setTimeout(function(){gettrailobj().visibility="visible"},500)}else{gettrailobj().visibility="visible"}
$("#btcontainer").data('imgid',imgid);divw=parseInt(thw)+25;divh=parseInt(thh)+25;mm_hoverThumb=1}
function trailOnI(thumbimg,imgid,thw,thh,smallThumbPath,imgtitle,delayhover){if(!gettrailobj()){return}
if(trailOff2.th===this){return}
var thumbimgprev=smallThumbPath;imgtitle=$("[id^=spn"+imgid+"] span").text()||imgtitle;$("[id^=spn"+imgid+"]").each(function(){setImportantStyle(this,{display:'none'})});gettrailobj().left="-500px";var html='<div class="dt-flyout-over">'+'<div class="dt-flyout-over-thumbnail">'+'<img border="0" width="'+thw+'" height="'+thh+'" src="'+thumbimgprev+'" id="btcontainer" name="btcontainer" style="display: block;">'+(imgtitle?'<div class="dt-flyout-over-title" style="width: '+(thw-10)+'px;">'+imgtitle.replace(/([.,!?]) *([^.,!?])/g,'$1 $2')+'</div>':'')+'</div>'+'</div>';gettrailobject().innerHTML=html;$("#btcontainer").data('imgid',imgid);$("#btcontainer").attr('src',$("[id^=bigthumb"+imgid+"]").attr('src'));$("#btcontainer").removeData('pi');$("#btcontainer").data('pi',new Image());$("#btcontainer").data('pi').onload=function(){if($("#btcontainer").data('pi')===this){$("#btcontainer").attr('src',this.src)}}
$("#btcontainer").data('pi').src=thumbimg;if(delayhover){if(trailOff2.t){clearTimeout(trailOff2.t)}
trailOff2.t=setTimeout(function(){gettrailobj().visibility="visible"},500)}else{gettrailobj().visibility="visible"}
divw=parseInt(thw)+25;divh=parseInt(thh)+130;mm_hoverThumb=1}
function trailOn2(thumbimg,imgtitle,username,imgid,imgsize,credit,level,thw,thh,smallmedium,smallThumbPath){return trailOnI.call(this,thumbimg,imgid,thw,thh,smallThumbPath,imgtitle)}
function trailOff2(e){if(trailOff2.t){clearTimeout(trailOff2.t)}
if(typeof e!='undefined'&&e.type&&' touchstart touchmove touchend '.indexOf(" "+e.type+" ")!=-1){trailOff2.th=this}else{delete trailOff2.th}
mm_hoverThumb=0;if(gettrailobj()){gettrailobj().visibility="hidden"}}
function computesize(width,height,src,hoverthumb){if(width/height>400/160){return[Math.round((width*160)/height),160,'/b/']}
if(width/height>400/450){return[400,Math.round((height*400)/width),hoverthumb||'/x/']}
return[Math.round((width*450)/height),450,hoverthumb||'/x/']}