DT.onReady(()=>{if(varSHget.s_sp!==''){document.querySelector('#s_sp').value=varSHget.s_sp}
if(varSHget.s_all!=''||(varSHget.s_st!=''&&varSHget.s_op!=''&&varSHget.s_mr!=''&&varSHget.s_rf!='y'&&varSHget.s_ed!='y'&&varSHget.s_exclusive!=''&&varSHget.s_wel!=''&&varSHget.s_pel!=''&&varSHget.s_srel!=''&&varSHget.s_orp!='y'&&varSHget.s_orl!='y'&&varSHget.s_ors!='y'&&varSHget.s_orw!='y'&&varSHget.s_clc!='y'&&varSHget.s_clm!='y'&&varSHget.s_c1e!=''&&varSHget.s_color1!=''&&varSHget.s_percent1!=''&&varSHget.s_c2e!=''&&varSHget.s_color2!=''&&varSHget.s_percent2!=''&&varSHget.s_rsf!='0'&&varSHget.s_rst!='7'&&varSHget.s_amf!=''&&varSHget.s_sp!=''&&varSHget.s_exc!=''&&varSHget.s_mrc1!='y'&&varSHget.s_mrc2!='y'&&varSHget.s_mrc3!='y'&&varSHget.s_mrc4!='y'&&varSHget.s_mrc5!='y'&&varSHget.s_mrg!='1'&&varSHget.s_mra1!=''&&varSHget.s_mra2!=''&&varSHget.s_mra3!=''&&varSHget.s_mra4!=''&&varSHget.s_mra5!=''&&varSHget.s_mra6!=''&&varSHget.s_mra7!=''&&varSHget.s_mra8!=''&&varSHget.s_mra9!=''&&varSHget.s_mrea!=''&&varSHget.s_mreb!=''&&varSHget.s_mreh!=''&&varSHget.s_mrem!=''&&varSHget.s_mrec!=''&&varSHget.s_mreo!=''&&varSHget.s_sl0!='y'&&varSHget.s_sl1!='y'&&varSHget.s_sl2!='y'&&s_sl3!='y'&&varSHget.s_sl4!='y'&&varSHget.s_sl5!='y'&&varSHget.firstvalue!='')){document.querySelector('#js-submit-button').classList.add('js-adv-filter-apply');document.querySelector('input[name="srh_field"]').addEventListener('keypress',function(e){if(e.which==13){try{if(puzzle.searchUrl(this.value))return!1}catch(e){}
document.querySelector('.js-adv-filter-apply').dispatchEvent(new Event('click'));return!1}})}else{var clickAdv=0;document.querySelector('#activ-adv-menu').addEventListener('click',function(){clickAdv++;if(clickAdv<=1){document.querySelector('#js-submit-button').classList.add('js-adv-filter-apply');document.querySelector('input[name="srh_field"]').addEventListener('keypress',function(e){if(e.which==13){try{if(puzzle.searchUrl(this.value))return!1}catch(e){}
document.querySelector('.js-adv-filter-apply').dispatchEvent(new Event('click'));return!1}})}})}
const openMobileFilters=document.querySelector('.js-open-filters-mobile');if(!openMobileFilters.hasAttribute('data-guest')){openMobileFilters.addEventListener('click',function(event){event.stopPropagation?event.stopPropagation():event.cancelBubble=!0;event.preventDefault();DT.Scheduler.postTask(()=>{DT.UI.set('#activ-adv-menu','opened')},{priority:'user-blocking'})})}
const openTabletFilters=document.querySelector('.js-open-filters-tablet');if(!openTabletFilters.hasAttribute('data-guest')){openTabletFilters.addEventListener('click',function(event){event.stopPropagation?event.stopPropagation():event.cancelBubble=!0;event.preventDefault();DT.UI.set('#activ-adv-menu','opened')})}
const closeMobileFilters=document.querySelector('.adv-search__close');closeMobileFilters.addEventListener('click',function(event){event.stopPropagation?event.stopPropagation():event.cancelBubble=!0;event.preventDefault();DT.Scheduler.postTask(()=>{DT.UI.set('#activ-adv-menu','closed')},{priority:'user-visible'})});document.querySelectorAll(".js-adv-filter-apply").forEach(function(elem){elem.addEventListener("click",function(event){event.stopPropagation?event.stopPropagation():event.cancelBubble=!0;event.preventDefault();setTimeout(function(){searchSubmitFilters(elem.id)},1000)})});document.getElementById('srh_fieldwrs').addEventListener('change',function(){changeEvent(1);searchSubmitFilters()});let inputMedia=document.querySelectorAll('.js-input-action');let typingTimer;let doneTypingInterval=3000;inputMedia.forEach(input=>{input.addEventListener('keyup',async function(e){e.stopPropagation();e.preventDefault();await DT.Scheduler.yieldToMain();let field=this.id;let value=document.getElementById(field).value;if(value&&field==='srh_fieldwrs'){clearTimeout(typingTimer);typingTimer=setTimeout(function(){searchSubmitFilters()},doneTypingInterval)}})});if(varSHget.s_all=='y'){DT.UI.set('#s_allm','active')}
if(varSHget.s_ph=='y'){DT.UI.set('#s_phm','active')}
if(varSHget.s_il=='y'){DT.UI.set('#s_ilm','active')}
if(varSHget.s_video=='y'){DT.UI.set('#s_videom','active')}
if(varSHget.s_audio=='y'){DT.UI.set('#s_audiom','active')}
if((varSHget.s_ph=='y'&&varSHget.s_il=='y'&&varSHget.s_video=='y'&&varSHget.s_audio=='y')||varSHget.s_all=='y'){DT.UI.set('#s_allm','active');["s_phm","s_ilm","s_videom","s_audiom"].forEach(id=>DT.UI.unset("#"+id))}
var specifiedElement=document.getElementById('activ-adv-menu');var inputsearch=document.getElementById('searchfrm');var didyoumean=document.getElementsByClassName("didyoumean")[0];document.addEventListener('click',async function(event){await DT.Scheduler.yieldToMain();if(typeof specifiedElement!=='undefined'&&typeof inputsearch!=='undefined'){var isClickInside=specifiedElement&&specifiedElement.contains(event.target);var isClickInputSh=inputsearch&&inputsearch.contains(event.target);if(isClickInside===!1&&isClickInputSh===!1){cloaseAllFilters();if(changeEvent(2)==1)
searchSubmitFilters();return!1}}});document.querySelectorAll('.contenttype').forEach(function(element){element.addEventListener('click',async function(event){event.stopPropagation?event.stopPropagation():event.cancelBubble=!0;event.preventDefault();await DT.Scheduler.yieldToMain();changeEvent(1);varSHget.s_all='n';varSHget.s_ph='n';varSHget.s_il='n';varSHget.s_video='n';varSHget.s_audio='n';if(element.getAttribute('data-state')==='active'){DT.UI.unset('#'+this.id);if(this.id==='s_allm')document.getElementById('s_all').checked=!1;if(this.id==='s_phm')document.getElementById('s_ph').checked=!1;if(this.id==='s_ilm')document.getElementById('s_il').checked=!1;if(this.id==='s_videom')document.getElementById('s_video').checked=!1;if(this.id==='s_audiom')document.getElementById('s_audio').checked=!1}else{DT.UI.set('#'+this.id,'active');if(this.id==='s_allm')document.getElementById('s_all').checked=!0;if(this.id==='s_phm')document.getElementById('s_ph').checked=!0;if(this.id==='s_ilm')document.getElementById('s_il').checked=!0;if(this.id==='s_videom')document.getElementById('s_video').checked=!0;if(this.id==='s_audiom')document.getElementById('s_audio').checked=!0;if(this.id==='s_phm'||this.id==='s_ilm'){DT.UI.unset("#s_allm");DT.UI.unset("#s_videom");DT.UI.unset("#s_audiom");document.getElementById('s_all').checked=!1;document.getElementById('s_video').checked=!1;document.getElementById('s_audio').checked=!1}
if(this.id==='s_videom'){DT.UI.unset("#s_allm");DT.UI.unset("#s_phm");DT.UI.unset("#s_ilm");DT.UI.unset("#s_audiom");document.getElementById('s_all').checked=!1;document.getElementById('s_ph').checked=!1;document.getElementById('s_audio').checked=!1}
if(this.id==='s_audiom'){DT.UI.unset("#s_allm");DT.UI.unset("#s_phm");DT.UI.unset("#s_ilm");DT.UI.unset("#s_videom");document.getElementById('s_all').checked=!1;document.getElementById('s_ph').checked=!1;document.getElementById('s_il').checked=!1;document.getElementById('s_video').checked=!1}
if(this.id==='s_allm'){DT.UI.unset("#s_audiom");DT.UI.unset("#s_phm");DT.UI.unset("#s_ilm");DT.UI.unset("#s_videom");varSHget.s_all='y';document.getElementById('s_ph').checked=!1;document.getElementById('s_il').checked=!1;document.getElementById('s_video').checked=!1;document.getElementById('s_audio').checked=!1}}
if(document.getElementById('s_allm').getAttribute('data-state')==='active'){varSHget.s_all='y'}
if(document.getElementById('s_phm').getAttribute('data-state')==='active'){varSHget.s_ph='y'}
if(document.getElementById('s_ilm').getAttribute('data-state')==='active'){varSHget.s_il='y'}
if(document.getElementById('s_videom').getAttribute('data-state')==='active'){varSHget.s_video='y'}
if(document.getElementById('s_audiom').getAttribute('data-state')==='active'){varSHget.s_audio='y'}})});var resetElement=document.querySelector('.reset');if(resetElement){resetElement.addEventListener('click',function(){var searchstr=varSHget.site_adr+"search.php?securitycheck="+securitycheck+"&firstvalue="+varSHget.firstvalue+"&srh_field="+varSHget.srh_field+"&s_all="+varSHget.s_all+"&s_ph="+varSHget.s_ph+"&s_il="+varSHget.s_il+"&s_video="+varSHget.s_video+"&s_video="+varSHget.s_video+"&s_audio="+varSHget.s_audio+"&s_ad="+varSHget.s_ad+"&s_free="+varSHget.s_free;searchstr=searchstr+"&nd=1";window.location.href=searchstr})}})